version: 0.2            
phases:
  install:
  - echo "installing"
  pre_build:
    commands:
  build:
    commands:
    finally:
  post_build:
    commands:
    finally:
# artifacts:
#   files:
#   discard-paths: yes
#   base-directory: location
#   secondary-artifacts:
#     artifactIdentifier:
#       files:
#         - location
#         - location
#       discard-paths: yes
#       base-directory: location
#     artifactIdentifier:
#       files:
#         - location
#         - location
#       discard-paths: yes
#       base-directory: location
# cache:
#   paths:
#     - path
#     - path
